leftnav:
- identifier: 9b5c443f-c555-e0df-fcbc-4ef11f9dca22
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 02a08f32-b55a-9eae-093a-ea89bc52f9ff
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: a482c984-f53f-c6e7-7225-266c8220cdfc
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 2513eff9-31ab-d9d4-c325-1fb35fed8981
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 47485b70-a0f4-dc83-a50b-d38f6c9950c4
  name: Projects
  pageRef: /pages/projects
  weight: 50
